### ISSUE TITLE
Wagtail React Streamfield Support

### ISSUE THREAD

**Issue by KalobTaulien** [FlipperPA/wagtailcodeblock#15]
Hey there, 

I really like this package. I went to install it on a project I have that's using [wagtail react streamfields](https://github.com/wagtail/wagtail-react-streamfield) and it doesn't show the preview. Something in DOM has probably changed. 

I just thought I should bring this up as it's looking like it'll be added to Wagtail 2.6 which should be out in a few months. [This is the pull request I'm referring to](https://github.com/wagtail/wagtail/pull/4942)

**Comment by FlipperPA** [comment]
Thanks for the heads up! Once we get to an alpha of 2.6, I'll go ahead and make the changes, @KalobTaulien.

**Comment by FlipperPA** [comment]
Hey @KalobTaulien, I'm going to be tackling this with the 2.7 release candidate out now... and it's probably time to add a `pytest-django` test suite.

**Comment by FlipperPA** [comment]
This has been release as `wagtailcodeblock==1.17.1.0` on PyPI. Thanks again, @KalobTaulien!
