### ISSUE TITLE
Problem with the code label

### ISSUE THREAD

**Issue by LunatikDev** [FlipperPA/wagtailcodeblock#21]
Hi, i have a code label that is added from nowhere and i can't remove it, there is nothing in the template that adds that but still the following code is added on the page:

![image](https://user-images.githubusercontent.com/58997519/77985563-d6320880-72e2-11ea-9ae1-2225174811b8.png)
 
and the result is that:

![image](https://user-images.githubusercontent.com/58997519/77985358-3ffde280-72e2-11ea-8845-478af9786090.png)

How to proceed to remove that label ?

**Comment by enzedonline** [comment]
I have the same issue. Did you ever find a solution?

**Comment by enzedonline** [comment]
> Hi, i have a code label that is added from nowhere and i can't remove it, there is nothing in the template that adds that but still the following code is added on the page:
> 
> ![image](https://user-images.githubusercontent.com/58997519/77985563-d6320880-72e2-11ea-9ae1-2225174811b8.png)
> 
> and the result is that:
> 
> ![image](https://user-images.githubusercontent.com/58997519/77985358-3ffde280-72e2-11ea-8845-478af9786090.png)
> 
> How to proceed to remove that label ?

I have the same issue. Did you ever find a solution?

**Comment by FlipperPA** [comment]
@enzedonline @LunatikDev I believe this was injected by some old JavaScript which is no longer used. We've done a major rewrite of the asset pipeline. Can you try again? I'm going to go ahead and close this issue, but please open another with the latest version, if you're still seeing an issue. Thanks!
