### ISSUE TITLE
Disable line numbering ?

### ISSUE THREAD

**Issue by nigfinch** [FlipperPA/wagtailcodeblock#22]
How do you disable line numbering for the code block in the django template ?

**Comment by chriswedgwood** [comment]
You can just override the template i.e. move code_block.html from site-packages and remove class="line-numbers" from pre tag 👍 

![image](https://user-images.githubusercontent.com/1273523/128083138-53f05292-043f-4834-acdf-99620f1dfe67.png)

**Comment by FlipperPA** [comment]
Better late than never, I've made this a settings option, `WAGTAIL_CODE_BLOCK_LINE_NUMBERS`; set it to `False` in your Django settings and you'll be good to go. Going out in a new version in about 10 minutes.

**Comment by FlipperPA** [comment]
Release in version `1.25.0.1`.
