### ISSUE TITLE
Admin Clientside Error - Wagtail Release >= 2.13

### ISSUE THREAD

**Issue by dutrowe** [FlipperPA/wagtailcodeblock#28]
Clientside error on admin when using wagtailcodeblock "_**Uncaught ReferenceError: Prism is not defined at prism_repaint**_". I believe its due to Wagtail recent releases; the error is shown when using versions >= 2.13. 

When viewing the page live everything works fine, the error is only shown on the Wagtail Admin.

![image](https://user-images.githubusercontent.com/50187786/134525755-a973b1bb-9960-47d7-9efa-503480e04f05.png)

**Comment by cybelew** [comment]
I've created a PR above that should fix this issue for Wagtail 2.13+.
