### ISSUE TITLE
Front end display template.

### ISSUE THREAD

**Issue by FlipperPA** [FlipperPA/wagtailcodeblock#3]

**Comment by MiltonLn** [comment]
Hello, Tim.

What do you mean with this issue? because i was thinking about a feature in which you can switch the prismjs themes to handle different code styles. Please see: https://github.com/PrismJS/prism-themes

Is this the same thing?
If not, what do you think of this feature?

**Comment by FlipperPA** [comment]
Ah, these were reminders while this was still a work in progress. I'll close them!

**Comment by MiltonLn** [comment]
But, what do you think of the feature i mentioned?

**Comment by FlipperPA** [comment]
Isn't that what I have here? You can set this to use any of the languages you want in the dropdown:

https://github.com/FlipperPA/wagtailcodeblock#django-settings

**Comment by MiltonLn** [comment]
No, what i mean is to switch between color themes like these https://github.com/PrismJS/prism-themes

**Comment by SalahAdDin** [comment]
@MiltonLn I think we can make a new tag for it, a new setting for rendering, actually i did implmented my own code block with other `highlighter` but it is very simple and don't render the code in the admin page.

**Comment by FlipperPA** [comment]
I do like this idea, I just haven't had to cycles to get it done.

**Comment by MiltonLn** [comment]
@FlipperPA hey!, could you take a look at my PR review of puput for stream fields?

**Comment by SalahAdDin** [comment]
@MiltonLn can you put link here? By my side i did this PR: https://github.com/FlipperPA/wagtailcodeblock/pull/4

**Comment by SalahAdDin** [comment]
@FlipperPA can you review my PR?
