### ISSUE TITLE
404's for some non existent CDNJS files

### ISSUE THREAD

**Issue by fourfridays** [FlipperPA/wagtailcodeblock#38]
## Version Number
prism.js 1.29.0
Wagtail 5.0

## Problem Statement
- When copy-to-cipboard option is set to True the app tries to get the following non-existent file `https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.css` that returns a 404 in the browser console.
- When syntax highlighter language is set to HTML the app tries to get the following non-existent file `https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-html.min.js` and returns a 404 in the browser console

## Proposed Solution
For the copy-to-clipboard 404 error we can drop the following code:
https://github.com/FlipperPA/wagtailcodeblock/blob/f0ceaaba3b36eb9f0dc487359fa29518b0402396/wagtailcodeblock/templatetags/wagtailcodeblock_tags.py#L82

For the HTML language 404 we can add if language check:
https://github.com/FlipperPA/wagtailcodeblock/blob/f0ceaaba3b36eb9f0dc487359fa29518b0402396/wagtailcodeblock/templates/wagtailcodeblock/code_block.html#L17

**Comment by fourfridays** [comment]
I can do a PR over the weekend for this @FlipperPA

**Comment by FlipperPA** [comment]
Thanks @fourfridays - great sleuthing, I had been meaning to track this down. I'll look for the PR early next week!
