### ISSUE TITLE
Remvove depreciated warning  insert_editor_css

### ISSUE THREAD

**Issue by Raidm404** [FlipperPA/wagtailcodeblock#41]
Please replace insert_editor_css with insert_global_admin_css   in  wagtailcodeblock/wagtail_hooks.py

**Comment by FlipperPA** [comment]
Thanks! Yeah, we need to take care of this deprecation. I'll get it into the next release. Cheers.

**Comment by FlipperPA** [comment]
Done! Thanks, this'll go out in the next release.
