### ISSUE TITLE
Template tags for rendering

### ISSUE THREAD

**Issue by SalahAdDin** [FlipperPA/wagtailcodeblock#5]
Hey, thank you for you work.

I'm using your package and i'm trying to improve it, you can see my pr about it.

I'm thinking about how can i render the code block and i did make this in my code:
```html
<div class="">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.3/themes/prism-coy.min.css"
          rel="stylesheet"/>
    <pre>
        <code class="language-{{ self.code.language }}">{{ self.code.code }}</code>
    </pre>
    {% if self.reference %}
        <div class="caption">
            Reference <a href="{{ self.reference }}">here.</a>
        </div>
    {% endif %}
    <script defer
            src='https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.3/prism.min.js'></script>
    <script defer
            src='https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.3/components/prism-{{ self.code.language }}.min.js'></script>
</div>
```

This is the template for my code; but if you think about it, if i have many code blocks in the body, this template will be rendered many times, getting the same template one by one time, the same template. But it is only useful with the specify language page, getting the other two files won't be useful and it will terrible for performance too.

We have two options, put in the documentation that user have to render it in the base template, or create a template tag. I think the second option will be better, why? Because actually we have two get the latest version, and because we want too have our template.

I was thinking about print the theme option in the [template](https://stackoverflow.com/questions/4836641/django-how-to-use-settings-in-templates), but i think it isn't a securely option.

In addition, if we load the `prism` main file in a template tag in script body, we have to upload the specific language files after it, so, we have to make other template tag, or, create one that update first this file, and after the other files, in the same way that admin(it could have a difficult getting all code laguange values from the body. If you put the specific file before the main file, the highlighting will be wrong.

So, what do you think about it?

**Comment by SalahAdDin** [comment]
@FlipperPA https://github.com/FlipperPA/wagtailcodeblock/pull/6

**Comment by SalahAdDin** [comment]
@FlipperPA What do you thınk about my work?

**Comment by FlipperPA** [comment]
@SalahAdDin Hello old friend! Just cleaning up some old issues. I think we got this sorted a while back. :)
